map  <leader><leader>f <Plug>(easymotion-bd-f)
nmap <leader><leader>s <Plug>(easymotion-overwin-f2)
map  <leader><leader>w <Plug>(easymotion-bd-w)
map  <leader><leader>W <Plug>(easymotion-bd-W)
map  <leader><leader>e <Plug>(easymotion-bd-e)
map  <leader><leader>E <Plug>(easymotion-bd-E)
map  <leader><leader>t <Plug>(easymotion-bd-t)
